 DROP TABLE SPROCESS;
GO
CREATE TABLE SPROCESS (

SERV_PROV_CODE varchar(15) NOT NULL,
R1_PROCESS_CODE varchar(70) NOT NULL,
SD_STP_NUM int NOT NULL,
SD_PRO_ID1 varchar(24) NULL,
SD_NXT_ID1 varchar(24) NULL,
SD_PRO_DES varchar(100) NULL,
SD_BUREAU_CODE varchar(8) NULL,
SD_DIVISION_CODE varchar(8) NULL,
SD_GROUP_CODE varchar(8) NULL,
SD_SECTION_CODE varchar(8) NULL,
SD_OFFICE_CODE varchar(8) NULL,
SD_DUE_DAY smallint NULL,
SD_COMMENT varchar(240) NULL,
SD_ACT_GRP varchar(30) NULL,
SD_ACT_TYP varchar(30) NULL,
SD_ACT_DES varchar(30) NULL,
SD_APP_COD varchar(4) NULL,
SD_APP_DES varchar(200) NULL,
SD_STAT_DES varchar(30) NULL,
SD_STAT_COD varchar(4) NULL,
SD_CHK_LV1 varchar(1) NULL,
SD_CHK_LV2 varchar(1) NULL,
SD_CHK_LV3 varchar(1) NULL,
SD_CHK_LV4 varchar(1) NULL,
SD_CHK_LV5 varchar(1) NULL,
SD_PROCED varchar(30) NULL,
REC_DATE datetime NOT NULL,
REC_FUL_NAM varchar(70) NOT NULL,
REC_STATUS varchar(1) NULL,
SD_AGENCY_CODE varchar(8) NULL,
ASGN_AGENCY_CODE varchar(8) NULL,
ASGN_BUREAU_CODE varchar(8) NULL,
ASGN_DIVISION_CODE varchar(8) NULL,
ASGN_GROUP_CODE varchar(8) NULL,
ASGN_SECTION_CODE varchar(8) NULL,
ASGN_OFFICE_CODE varchar(8) NULL,
ASGN_FNAME varchar(70) NULL,
ASGN_MNAME varchar(70) NULL,
ASGN_LNAME varchar(70) NULL,
R1_CHECKBOX_GROUP varchar(30) NULL,
R1_CHECKBOX_CODE varchar(30) NULL,
HOURS_SPENT_REQUIRED varchar(1) NULL,
CALENDAR_ID bigint NULL,
RES_ID bigint NULL,
DISPLAY_IN_ACA varchar(1) NULL,
ESTIMATED_HOURS numeric(5,2) NULL,
SD_PRO_ORD bigint NULL,

CONSTRAINT PK_SPROCESS PRIMARY KEY (
SERV_PROV_CODE,
R1_PROCESS_CODE,
SD_STP_NUM
)

);

-- ALTER TABLE SPROCESS ALTER COLUMN SD_CHK_LV1 varchar(5);
-- ALTER TABLE SPROCESS ALTER COLUMN SD_CHK_LV2 varchar(5);
-- ALTER TABLE SPROCESS ALTER COLUMN SD_CHK_LV3 varchar(5);
-- ALTER TABLE SPROCESS ALTER COLUMN SD_CHK_LV4 varchar(5);
-- ALTER TABLE SPROCESS ALTER COLUMN SD_CHK_LV5 varchar(5);