DROP TABLE R3STATYP
GO

CREATE TABLE R3STATYP (

R3_ACT_STAT_COD varchar(20) NOT NULL,
R3_ACT_TYPE_DES varchar(100) NULL,
R3_ACT_STAT_DES varchar(200) NOT NULL,
R3_ACT_STAT_FLG varchar(1) NOT NULL,
R3_ROLE varchar(30) NULL,
R3_APP_TYP_CODE varchar(3) NULL,
REC_DATE datetime NOT NULL,
REC_FUL_NAM varchar(70) NOT NULL,
REC_STATUS varchar(1) NULL,
SERV_PROV_CODE varchar(15) NOT NULL,
R3_PROCESS_CODE varchar(70) NOT NULL,
APPLICATION_STATUS varchar(30) NULL,
PARENT_STATUS varchar(200) NULL,
R3_MOU_CLOCK_ACTION varchar(10) NULL,
RES_ID bigint NULL,
DISPLAY_IN_ACA varchar(1) NULL,

CONSTRAINT PK_R3STATYP PRIMARY KEY (
SERV_PROV_CODE,
R3_ACT_STAT_COD,
R3_PROCESS_CODE
)

)