DROP TABLE SPROCESS_GROUP;
GO
CREATE TABLE SPROCESS_GROUP (

SERV_PROV_CODE varchar(15) NOT NULL,
RELATION_SEQ_ID bigint NOT NULL,
SPROCESS_GROUP_CODE varchar(70) NOT NULL,
PARENT_RELATION_SEQ_ID bigint NOT NULL,
SD_STP_NUM int NOT NULL,
R1_PROCESS_CODE varchar(70) NOT NULL,
REC_DATE datetime NOT NULL,
REC_FUL_NAM varchar(70) NOT NULL,
REC_STATUS varchar(1) NULL,
PARENTTASKNAME varchar(155) NULL,
SUBFLOW_COMPLETION_REQ varchar(1) NULL,
TASK_ACTIVATION varchar(1) NULL,
MODULE_NAME varchar(15) NULL,
RES_ID bigint NULL,

CONSTRAINT PK_SPROCESS_GROUP PRIMARY KEY (
SERV_PROV_CODE,
SPROCESS_GROUP_CODE,
PARENT_RELATION_SEQ_ID,
SD_STP_NUM
)

)