DROP TABLE IF EXISTS R3APPTYP;
GO

CREATE TABLE R3APPTYP (

SERV_PROV_CODE varchar(15) NOT NULL,
R1_PER_GROUP varchar(30) NOT NULL,
R1_PER_TYPE varchar(30) NOT NULL,
R1_PER_SUB_TYPE varchar(30) NOT NULL,
R1_PER_CATEGORY varchar(30) NOT NULL,

R1_FEE_CODE varchar(255) NULL,
R1_PROCESS_CODE varchar(70) NULL,
R1_CHCKBOX_CODE varchar(12) NULL,
R1_UDCODE1 varchar(12) NULL,
R1_UDCODE2 varchar(30) NULL,
R1_UDCODE3 varchar(12) NULL,
R1_PER_UDCODE1 varchar(12) NULL,

REC_DATE datetime NOT NULL,
REC_FUL_NAM varchar(70) NOT NULL,
REC_STATUS varchar(1) NULL,

R1_HR_EMAIL varchar(70) NULL,
R1_SMARTCHOICE_CODE varchar(40) NULL,
R1_ALT_SEQ_1 bigint NULL,
R1_ALT_MASK_1 varchar(200) NULL,
R1_ALT_SEQ_RESET_1 varchar(20) NULL,

R1_ALT_SEQ_2 bigint NULL,
R1_ALT_MASK_2 varchar(200) NULL,
R1_ALT_SEQ_RESET_2 varchar(20) NULL,

R1_IS_REBILL varchar(1) NULL,
R1_DOC_CODE varchar(40) NULL,
APP_STATUS_GROUP_CODE varchar(30) NULL,

R1_MODULE_NAME varchar(100) NULL,

TYPE_DISPORDER numeric(5,0) NULL,
SUBTYPE_DISPORDER numeric(5,0) NULL,
CATEGORY_DISPORDER numeric(5,0) NULL,

R1_SMARTCHOICE_CODE_FOR_ACA varchar(40) NULL,
R1_GIS_SERVICE_ID varchar(70) NULL,
R1_GIS_TYPE_ID varchar(70) NULL,

R1_RECEIPT_NBR_SCHEME varchar(200) NULL,
R1_ICON_NBR bigint NULL,

APP_DEFAULT_STATUS_CODE varchar(30) NULL,

COPY_ALL_ASSOCIATED_APO varchar(1) NULL,
ATTACHED_GIS varchar(1) NULL,
ATTACHED_APO varchar(1) NULL,

R1_APP_TYPE_ALIAS varchar(255) NULL,

R1_DUE_DAY numeric(4,0) NULL,
R1_PROD_UNIT_TYPE varchar(10) NULL,
R1_EST_PROD_UNITS numeric(15,2) NULL,
R1_VALUE_REQUIRED varchar(1) NULL,
R1_EST_COST_PER_UNIT numeric(15,2) NULL,

R6_ENFORCEMENT_TYPE varchar(30) NULL,
R1_DOC_CODE_FOR_ACA varchar(40) NULL,

ADDR_GROUP varchar(30) NULL,

CAPKEY_MASK_NAME varchar(255) NULL,
CAP_MASK_NAME varchar(255) NULL,
RECEIPT_MASK_NAME varchar(255) NULL,

IS_RENEWAL varchar(1) NULL,
IS_ISSUE varchar(1) NULL,

RENEWAL_GROUP varchar(30) NULL,
RENEWAL_TYPE varchar(30) NULL,
RENEWAL_SUB_TYPE varchar(30) NULL,
RENEWAL_CATEGORY varchar(30) NULL,

ACA_STATUS varchar(1) NULL,
RES_ID bigint NULL,

R1_ANONYMOUS_ALLOWED varchar(1) NULL,
R1_REGISTERUSR_ALLOWED varchar(1) NULL,
R1_LP_ALLOWED varchar(1) NULL,

IS_AMENDABLE varchar(1) NULL,
IVR_NUMBER varchar(6) NULL,

PAR_CAP_MASK_NAME varchar(255) NOT NULL,
TMP_CAP_MASK_NAME varchar(255) NOT NULL,

IS_INCOMPLETE varchar(1) NULL,
R1_FEE_CALC_FACTOR_FOR_ACA varchar(8) NULL,

INVOICE_MASK_NAME varchar(255) NULL,
ASSOCIATED_FORM_FLAG varchar(1) NULL,
R1_DEFAULT_DOC_TYPE varchar(250) NULL,

IS_SEARCHABLE varchar(1) NULL,
VIRTUAL_FOLDER_GROUP varchar(500) NULL,
R7_SEARCHABLE_IN_ACA varchar(1) NULL,
PARTIAL_SUBMISSION_FLAG varchar(1) NULL,
R1_ANONYMOUS_CREATE_ALLOWED varchar(1) NULL,
AS_CHILD_ONLY varchar(1) NULL,

APPTYP_HTML_INSTRUCTION varchar(max) NULL,
APPTYP_PLAIN_INSTRUCTION varchar(max) NULL,

IS_RENEWAL_OVERRIDE varchar(1) NULL,

AUDIT_INIT_BY varchar(70) NULL,
AUDIT_INIT_DATE datetime NULL,
AUDIT_MOD_BY varchar(70) NULL,
AUDIT_MOD_DATE datetime NULL,

AUTO_COPY_RENEWAL varchar(1) NULL,
AUTO_COPY_OPTIONS varchar(1000) NULL,
RENEWAL_COMPLETION_REQUIRED varchar(1) NULL,
RENEWAL_TASK_NAME varchar(100) NULL,
RENEWAL_APPROVAL_STATUS varchar(50) NULL,
RENEWAL_DENIAL_STATUS varchar(50) NULL,
RENEWAL_RECORD_STATUS varchar(50) NULL,

CONSTRAINT PK_R3APPTYP PRIMARY KEY (
SERV_PROV_CODE,
R1_PER_GROUP,
R1_PER_TYPE,
R1_PER_SUB_TYPE,
R1_PER_CATEGORY
)

);
GO