DROP TABLE IF EXISTS R2CHCKBOX;

CREATE TABLE R2CHCKBOX(

SERV_PROV_CODE varchar(15) NOT NULL,
R1_CHECKBOX_CODE varchar(12) NOT NULL,
R1_CHECKBOX_TYPE varchar(30) NOT NULL,
R1_CHECKBOX_DESC varchar(100) NOT NULL,
R1_CHECKBOX_IND varchar(1) NULL,
REC_DATE datetime NOT NULL,
REC_FUL_NAM varchar(70) NOT NULL,
REC_STATUS varchar(1) NULL,
R1_DISPLAY_ORDER int NOT NULL,
R1_FEE_INDICATOR varchar(30) NULL,
R1_ATTRIBUTE_VALUE varchar(200) NULL,
R1_ATTRIBUTE_UNIT_TYPE varchar(10) NULL,
R1_ATTRIBUTE_VALUE_REQ_FLAG varchar(1) NULL,
R1_VALIDATION_SCRIPT_NAME varchar(70) NULL,
R1_SEARCHABLE_FLAG varchar(1) NULL,
R1_CHECKBOX_GROUP varchar(30) NOT NULL,
R1_TASK_STATUS_REQ_FLAG varchar(10) NULL,
MAX_LENGTH smallint NULL,
DISPLAY_LENGTH smallint NULL,
R1_DEFAULT_SELECTED varchar(1) NULL,
R1_GROUP_DISPLAY_ORDER int NULL,
VCH_DISP_FLAG varchar(1) NULL,
R1_TABLE_GROUP_NAME varchar(255) NULL,
LOCATION_QUERY_FLAG varchar(1) NULL,
DEFAULT_APO_GIS_LAYER varchar(70) NULL,
R1_REQ_FEE_CALC varchar(1) NULL,
R1_SUPERVISOR_EDIT_ONLY_FLAG varchar(1) NULL,
R1_SHARED_DDLIST_ID bigint NULL,
RES_ID bigint NULL,
R1_ALIGNMENT varchar(1) NULL,
R1_DISABLE_SORT_TABLE varchar(1) NULL,
R1_SEARCHABLE_FOR_ACA varchar(1) NULL,
R1_CHECKBOX_DESC_ALT varchar(900) NULL,
R1_DISPLAY_LIC_VERIF_ACA varchar(1) NULL,
R1_CHECKBOX_DESC_ALIAS varchar(100) NULL,
AUDIT_INIT_DATE datetime NULL,
AUDIT_INIT_BY varchar(70) NULL,
AUDIT_MOD_DATE datetime NULL,
AUDIT_MOD_BY varchar(70) NULL,

CONSTRAINT PK_R2CHCKBOX PRIMARY KEY
(
SERV_PROV_CODE,
R1_CHECKBOX_CODE,
R1_CHECKBOX_TYPE,
R1_CHECKBOX_DESC,
R1_CHECKBOX_GROUP
)

);


ALTER TABLE R2CHCKBOX
ALTER COLUMN R1_CHECKBOX_DESC_ALIAS VARCHAR(1000);