-- DROP TABLE SPROCESS_KPI;

CREATE TABLE SPROCESS_KPI (

SERV_PROV_CODE VARCHAR(15) NOT NULL,
R1_PROCESS_CODE VARCHAR(70) NOT NULL,
SD_PRO_DES VARCHAR(100) NOT NULL,
SD_APP_DES VARCHAR(100) NOT NULL,

TIME_OWNER VARCHAR(20),

RECORD_FINAL VARCHAR(20),
ERROR_TYPE VARCHAR(20),
SUPER_GROUP VARCHAR(100),

REC_FUL_NAME VARCHAR(70),
REC_DATE DATETIME,
REC_STATUS CHAR(1),

AUDIT_INIT_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
AUDIT_INIT_BY VARCHAR(70),
AUDIT_MOD_DATE DATETIME,
AUDIT_MOD_BY VARCHAR(70),

CONSTRAINT PK_SPROCESS_KPI PRIMARY KEY (
SERV_PROV_CODE,
R1_PROCESS_CODE,
SD_PRO_DES,
SD_APP_DES
)

);