--DROP TABLE RSERV_WORKDAYS;

CREATE TABLE RSERV_WORKDAYS (

SERV_PROV_CODE VARCHAR(15) NOT NULL,
R1_PER_GROUP VARCHAR(30) NOT NULL,
DayName VARCHAR(30) NOT NULL,
DayOfWeek INT NOT NULL,

IsWorkingDay CHAR(1),
DayStartTime TIME,
DayEndTime TIME,
WorkingHours DECIMAL(5,2),

REC_FUL_NAME VARCHAR(70),
REC_DATE DATETIME,
REC_STATUS CHAR(1),

AUDIT_INIT_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
AUDIT_INIT_BY VARCHAR(70),
AUDIT_MOD_DATE DATETIME,
AUDIT_MOD_BY VARCHAR(70),

CONSTRAINT PK_RSERV_WORKDAYS PRIMARY KEY (
SERV_PROV_CODE,
R1_PER_GROUP,
DayOfWeek
)

);