--DROP TABLE R3APPTYPE_COMPLAINT;

CREATE TABLE R3APPTYPE_COMPLAINT (

SERV_PROV_CODE VARCHAR(15) NOT NULL,
R1_PER_GROUP VARCHAR(30) NOT NULL,
R1_PER_TYPE VARCHAR(30) NOT NULL,
R1_PER_SUB_TYPE VARCHAR(30) NOT NULL,
R1_PER_CATEGORY VARCHAR(30) NOT NULL,

R1_APP_TYPE_ALIAS VARCHAR(255),
R1_CHECKBOX_DESC VARCHAR(1000),

REC_FUL_NAME VARCHAR(70),
REC_DATE DATETIME,
REC_STATUS VARCHAR(1),

AUDIT_INIT_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
AUDIT_INIT_BY VARCHAR(70),
AUDIT_MOD_DATE DATETIME,
AUDIT_MOD_BY VARCHAR(70),

CONSTRAINT PK_COMPLAINT PRIMARY KEY (
SERV_PROV_CODE,
R1_PER_GROUP,
R1_PER_TYPE,
R1_PER_SUB_TYPE,
R1_PER_CATEGORY
)

);