USE ACCELA_KPI
GO

-- SELECT *
-- FROM SPROCESS s
-- LEFT JOIN SPROCESS_KPI_MAP m
-- ON s.SERV_PROV_CODE = m.SERV_PROV_CODE
-- AND s.R1_PROCESS_CODE = m.R1_PROCESS_CODE


SELECT *
FROM SPROCESS s
LEFT JOIN SPROCESS_KPI_MAP m
ON s.SERV_PROV_CODE = m.SERV_PROV_CODE
AND s.R1_PROCESS_CODE = m.R1_PROCESS_CODE
AND s.SD_PRO_DES = m.TASK_NAME
AND s.SD_APP_DES = m.STATUS_NAME;