INSERT INTO R3STATYP
(
R3_ACT_STAT_COD,
R3_ACT_TYPE_DES,
R3_ACT_STAT_DES,
R3_ACT_STAT_FLG,
R3_ROLE,
R3_APP_TYP_CODE,
REC_DATE,
REC_FUL_NAM,
REC_STATUS,
SERV_PROV_CODE,
R3_PROCESS_CODE,
APPLICATION_STATUS,
PARENT_STATUS,
R3_MOU_CLOCK_ACTION,
RES_ID,
DISPLAY_IN_ACA
)

SELECT
TRIM(R3_ACT_STAT_COD),
TRIM(R3_ACT_TYPE_DES),
TRIM(R3_ACT_STAT_DES),
TRIM(R3_ACT_STAT_FLG),
TRIM(R3_ROLE),
LEFT(TRIM(R3_APP_TYP_CODE),1),

TRY_CAST(REC_DATE AS DATETIME),
TRIM(REC_FUL_NAM),
LEFT(TRIM(REC_STATUS),1),

TRIM(SERV_PROV_CODE),
TRIM(R3_PROCESS_CODE),

TRIM(APPLICATION_STATUS),
TRIM(PARENT_STATUS),
TRIM(R3_MOU_CLOCK_ACTION),

TRY_CAST(NULLIF(RES_ID,'') AS BIGINT),
LEFT(TRIM(DISPLAY_IN_ACA),1)

FROM RAW_R3STATYP;

--SELECT top 3 *FROM R3STATYP