INSERT INTO SPROCESS_GROUP
SELECT

SERV_PROV_CODE,
TRY_CAST(RELATION_SEQ_ID AS BIGINT),
SPROCESS_GROUP_CODE,
TRY_CAST(PARENT_RELATION_SEQ_ID AS BIGINT),
TRY_CAST(SD_STP_NUM AS INT),
R1_PROCESS_CODE,

TRY_CAST(REC_DATE AS DATETIME),
REC_FUL_NAM,
LEFT(TRIM(REC_STATUS),1),

PARENTTASKNAME,
LEFT(TRIM(SUBFLOW_COMPLETION_REQ),1),
LEFT(TRIM(TASK_ACTIVATION),1),
MODULE_NAME,

TRY_CAST(RES_ID AS BIGINT)

FROM RAW_SPROCESS_GROUP;