INSERT INTO R3APPTYP
SELECT

SERV_PROV_CODE,
R1_PER_GROUP,
R1_PER_TYPE,
R1_PER_SUB_TYPE,
R1_PER_CATEGORY,

R1_FEE_CODE,
R1_PROCESS_CODE,
R1_CHCKBOX_CODE,
R1_UDCODE1,
R1_UDCODE2,
R1_UDCODE3,
R1_PER_UDCODE1,

TRY_CAST(REC_DATE AS DATETIME),
REC_FUL_NAM,
LEFT(TRIM(REC_STATUS),1),

R1_HR_EMAIL,
R1_SMARTCHOICE_CODE,

TRY_CAST(R1_ALT_SEQ_1 AS BIGINT),
R1_ALT_MASK_1,
R1_ALT_SEQ_RESET_1,

TRY_CAST(R1_ALT_SEQ_2 AS BIGINT),
R1_ALT_MASK_2,
R1_ALT_SEQ_RESET_2,

LEFT(TRIM(R1_IS_REBILL),1),
R1_DOC_CODE,
APP_STATUS_GROUP_CODE,

R1_MODULE_NAME,

TRY_CAST(TYPE_DISPORDER AS NUMERIC(5,0)),
TRY_CAST(SUBTYPE_DISPORDER AS NUMERIC(5,0)),
TRY_CAST(CATEGORY_DISPORDER AS NUMERIC(5,0)),

R1_SMARTCHOICE_CODE_FOR_ACA,
R1_GIS_SERVICE_ID,
R1_GIS_TYPE_ID,
R1_RECEIPT_NBR_SCHEME,

TRY_CAST(R1_ICON_NBR AS BIGINT),

APP_DEFAULT_STATUS_CODE,

LEFT(TRIM(COPY_ALL_ASSOCIATED_APO),1),
LEFT(TRIM(ATTACHED_GIS),1),
LEFT(TRIM(ATTACHED_APO),1),

R1_APP_TYPE_ALIAS,

TRY_CAST(R1_DUE_DAY AS NUMERIC(4,0)),
R1_PROD_UNIT_TYPE,
TRY_CAST(R1_EST_PROD_UNITS AS NUMERIC(15,2)),

LEFT(TRIM(R1_VALUE_REQUIRED),1),

TRY_CAST(R1_EST_COST_PER_UNIT AS NUMERIC(15,2)),

R6_ENFORCEMENT_TYPE,
R1_DOC_CODE_FOR_ACA,

ADDR_GROUP,

CAPKEY_MASK_NAME,
CAP_MASK_NAME,
RECEIPT_MASK_NAME,

LEFT(TRIM(IS_RENEWAL),1),
LEFT(TRIM(IS_ISSUE),1),

RENEWAL_GROUP,
RENEWAL_TYPE,
RENEWAL_SUB_TYPE,
RENEWAL_CATEGORY,

LEFT(TRIM(ACA_STATUS),1),

TRY_CAST(RES_ID AS BIGINT),

LEFT(TRIM(R1_ANONYMOUS_ALLOWED),1),
LEFT(TRIM(R1_REGISTERUSR_ALLOWED),1),
LEFT(TRIM(R1_LP_ALLOWED),1),

LEFT(TRIM(IS_AMENDABLE),1),

IVR_NUMBER,

PAR_CAP_MASK_NAME,
TMP_CAP_MASK_NAME,

LEFT(TRIM(IS_INCOMPLETE),1),

R1_FEE_CALC_FACTOR_FOR_ACA,

INVOICE_MASK_NAME,

LEFT(TRIM(ASSOCIATED_FORM_FLAG),1),

R1_DEFAULT_DOC_TYPE,

LEFT(TRIM(IS_SEARCHABLE),1),

VIRTUAL_FOLDER_GROUP,

LEFT(TRIM(R7_SEARCHABLE_IN_ACA),1),
LEFT(TRIM(PARTIAL_SUBMISSION_FLAG),1),
LEFT(TRIM(R1_ANONYMOUS_CREATE_ALLOWED),1),
LEFT(TRIM(AS_CHILD_ONLY),1),

APPTYP_HTML_INSTRUCTION,
APPTYP_PLAIN_INSTRUCTION,

LEFT(TRIM(IS_RENEWAL_OVERRIDE),1),

AUDIT_INIT_BY,
TRY_CAST(AUDIT_INIT_DATE AS DATETIME),
AUDIT_MOD_BY,
TRY_CAST(AUDIT_MOD_DATE AS DATETIME),

LEFT(TRIM(AUTO_COPY_RENEWAL),1),

AUTO_COPY_OPTIONS,

LEFT(TRIM(RENEWAL_COMPLETION_REQUIRED),1),

RENEWAL_TASK_NAME,
RENEWAL_APPROVAL_STATUS,
RENEWAL_DENIAL_STATUS,
RENEWAL_RECORD_STATUS

FROM RAW_R3APPTYP;