INSERT INTO R2CHCKBOX
(
SERV_PROV_CODE,
R1_CHECKBOX_CODE,
R1_CHECKBOX_TYPE,
R1_CHECKBOX_DESC,
R1_CHECKBOX_IND,
REC_DATE,
REC_FUL_NAM,
REC_STATUS,
R1_DISPLAY_ORDER,
R1_FEE_INDICATOR,
R1_ATTRIBUTE_VALUE,
R1_ATTRIBUTE_UNIT_TYPE,
R1_ATTRIBUTE_VALUE_REQ_FLAG,
R1_VALIDATION_SCRIPT_NAME,
R1_SEARCHABLE_FLAG,
R1_CHECKBOX_GROUP,
R1_TASK_STATUS_REQ_FLAG,
MAX_LENGTH,
DISPLAY_LENGTH,
R1_DEFAULT_SELECTED,
R1_GROUP_DISPLAY_ORDER,
VCH_DISP_FLAG,
R1_TABLE_GROUP_NAME,
LOCATION_QUERY_FLAG,
DEFAULT_APO_GIS_LAYER,
R1_REQ_FEE_CALC,
R1_SUPERVISOR_EDIT_ONLY_FLAG,
R1_SHARED_DDLIST_ID,
RES_ID,
R1_ALIGNMENT,
R1_DISABLE_SORT_TABLE,
R1_SEARCHABLE_FOR_ACA,
R1_CHECKBOX_DESC_ALT,
R1_DISPLAY_LIC_VERIF_ACA,
R1_CHECKBOX_DESC_ALIAS,
AUDIT_INIT_DATE,
AUDIT_INIT_BY,
AUDIT_MOD_DATE,
AUDIT_MOD_BY
)

SELECT

SERV_PROV_CODE,
R1_CHECKBOX_CODE,
R1_CHECKBOX_TYPE,
R1_CHECKBOX_DESC,
LEFT(R1_CHECKBOX_IND,1),

TRY_CAST(REC_DATE AS DATETIME),
REC_FUL_NAM,
LEFT(REC_STATUS,1),

TRY_CAST(R1_DISPLAY_ORDER AS INT),
R1_FEE_INDICATOR,
R1_ATTRIBUTE_VALUE,
R1_ATTRIBUTE_UNIT_TYPE,
LEFT(R1_ATTRIBUTE_VALUE_REQ_FLAG,1),
R1_VALIDATION_SCRIPT_NAME,
LEFT(R1_SEARCHABLE_FLAG,1),
R1_CHECKBOX_GROUP,
LEFT(R1_TASK_STATUS_REQ_FLAG,1),

TRY_CAST(MAX_LENGTH AS SMALLINT),
TRY_CAST(DISPLAY_LENGTH AS SMALLINT),
LEFT(R1_DEFAULT_SELECTED,1),
TRY_CAST(R1_GROUP_DISPLAY_ORDER AS INT),
LEFT(VCH_DISP_FLAG,1),

R1_TABLE_GROUP_NAME,
LEFT(LOCATION_QUERY_FLAG,1),
DEFAULT_APO_GIS_LAYER,
LEFT(R1_REQ_FEE_CALC,1),
LEFT(R1_SUPERVISOR_EDIT_ONLY_FLAG,1),

TRY_CAST(R1_SHARED_DDLIST_ID AS BIGINT),
TRY_CAST(RES_ID AS BIGINT),

LEFT(R1_ALIGNMENT,1),
LEFT(R1_DISABLE_SORT_TABLE,1),
LEFT(R1_SEARCHABLE_FOR_ACA,1),

LEFT(R1_CHECKBOX_DESC_ALT,900),
LEFT(R1_DISPLAY_LIC_VERIF_ACA,1),
LEFT(R1_CHECKBOX_DESC_ALIAS,100),

TRY_CAST(AUDIT_INIT_DATE AS DATETIME),
LEFT(AUDIT_INIT_BY,70),

TRY_CAST(AUDIT_MOD_DATE AS DATETIME),
LEFT(AUDIT_MOD_BY,70)

FROM RAW_R2CHCKBOX
WHERE TRY_CAST(REC_DATE AS DATETIME) IS NOT NULL;

-- SELECT *
-- FROM RAW_R2CHCKBOX
-- WHERE TRY_CAST(REC_DATE AS DATETIME) IS NULL

-- SELECT TOP 10 *
-- FROM RAW_R2CHCKBOX