DROP TABLE IF EXISTS RAW_SPROCESS;
GO

CREATE TABLE RAW_SPROCESS (

SERV_PROV_CODE VARCHAR(MAX),
R1_PROCESS_CODE VARCHAR(MAX),
SD_STP_NUM VARCHAR(MAX),
SD_PRO_ID1 VARCHAR(MAX),
SD_NXT_ID1 VARCHAR(MAX),
SD_PRO_DES VARCHAR(MAX),
SD_BUREAU_CODE VARCHAR(MAX),
SD_DIVISION_CODE VARCHAR(MAX),
SD_GROUP_CODE VARCHAR(MAX),
SD_SECTION_CODE VARCHAR(MAX),
SD_OFFICE_CODE VARCHAR(MAX),
SD_DUE_DAY VARCHAR(MAX),
SD_COMMENT VARCHAR(MAX),
SD_ACT_GRP VARCHAR(MAX),
SD_ACT_TYP VARCHAR(MAX),
SD_ACT_DES VARCHAR(MAX),
SD_APP_COD VARCHAR(MAX),
SD_APP_DES VARCHAR(MAX),
SD_STAT_DES VARCHAR(MAX),
SD_STAT_COD VARCHAR(MAX),
SD_CHK_LV1 VARCHAR(MAX),
SD_CHK_LV2 VARCHAR(MAX),
SD_CHK_LV3 VARCHAR(MAX),
SD_CHK_LV4 VARCHAR(MAX),
SD_CHK_LV5 VARCHAR(MAX),
SD_PROCED VARCHAR(MAX),
REC_DATE VARCHAR(MAX),
REC_FUL_NAM VARCHAR(MAX),
REC_STATUS VARCHAR(MAX),
SD_AGENCY_CODE VARCHAR(MAX),
ASGN_AGENCY_CODE VARCHAR(MAX),
ASGN_BUREAU_CODE VARCHAR(MAX),
ASGN_DIVISION_CODE VARCHAR(MAX),
ASGN_GROUP_CODE VARCHAR(MAX),
ASGN_SECTION_CODE VARCHAR(MAX),
ASGN_OFFICE_CODE VARCHAR(MAX),
ASGN_FNAME VARCHAR(MAX),
ASGN_MNAME VARCHAR(MAX),
ASGN_LNAME VARCHAR(MAX),
R1_CHECKBOX_GROUP VARCHAR(MAX),
R1_CHECKBOX_CODE VARCHAR(MAX),
HOURS_SPENT_REQUIRED VARCHAR(MAX),
CALENDAR_ID VARCHAR(MAX),
RES_ID VARCHAR(MAX),
DISPLAY_IN_ACA VARCHAR(MAX),
ESTIMATED_HOURS VARCHAR(MAX),
SD_PRO_ORD VARCHAR(MAX)

);


















-- CREATE TABLE RAW_SPROCESS (

-- SERV_PROV_CODE varchar(50),
-- R1_PROCESS_CODE varchar(100),
-- SD_STP_NUM varchar(50),
-- SD_PRO_ID1 varchar(50),
-- SD_NXT_ID1 varchar(50),
-- SD_PRO_DES varchar(200),
-- SD_BUREAU_CODE varchar(50),
-- SD_DIVISION_CODE varchar(50),
-- SD_GROUP_CODE varchar(50),
-- SD_SECTION_CODE varchar(50),
-- SD_OFFICE_CODE varchar(50),
-- SD_DUE_DAY varchar(50),
-- SD_COMMENT varchar(500),
-- SD_ACT_GRP varchar(50),
-- SD_ACT_TYP varchar(50),
-- SD_ACT_DES varchar(50),
-- SD_APP_COD varchar(50),
-- SD_APP_DES varchar(200),
-- SD_STAT_DES varchar(50),
-- SD_STAT_COD varchar(50),
-- SD_CHK_LV1 varchar(50),
-- SD_CHK_LV2 varchar(50),
-- SD_CHK_LV3 varchar(50),
-- SD_CHK_LV4 varchar(50),
-- SD_CHK_LV5 varchar(50),
-- SD_PROCED varchar(50),
-- REC_DATE varchar(50),
-- REC_FUL_NAM varchar(100),
-- REC_STATUS varchar(10)

-- );