DROP TABLE IF EXISTS RAW_R3STATYP;
GO

CREATE TABLE RAW_R3STATYP (
R3_ACT_STAT_COD VARCHAR(MAX),
R3_ACT_TYPE_DES VARCHAR(MAX),
R3_ACT_STAT_DES VARCHAR(MAX),
R3_ACT_STAT_FLG VARCHAR(MAX),
R3_ROLE VARCHAR(MAX),
R3_APP_TYP_CODE VARCHAR(MAX),
REC_DATE VARCHAR(MAX),
REC_FUL_NAM VARCHAR(MAX),
REC_STATUS VARCHAR(MAX),
SERV_PROV_CODE VARCHAR(MAX),
R3_PROCESS_CODE VARCHAR(MAX),
APPLICATION_STATUS VARCHAR(MAX),
PARENT_STATUS VARCHAR(MAX),
R3_MOU_CLOCK_ACTION VARCHAR(MAX),
RES_ID VARCHAR(MAX),
DISPLAY_IN_ACA VARCHAR(MAX)
);