DROP TABLE IF EXISTS RAW_SPROCESS_GROUP;

CREATE TABLE RAW_SPROCESS_GROUP (
SERV_PROV_CODE VARCHAR(MAX),
RELATION_SEQ_ID VARCHAR(MAX),
SPROCESS_GROUP_CODE VARCHAR(MAX),
PARENT_RELATION_SEQ_ID VARCHAR(MAX),
SD_STP_NUM VARCHAR(MAX),
R1_PROCESS_CODE VARCHAR(MAX),
REC_DATE VARCHAR(MAX),
REC_FUL_NAM VARCHAR(MAX),
REC_STATUS VARCHAR(MAX),
PARENTTASKNAME VARCHAR(MAX),
SUBFLOW_COMPLETION_REQ VARCHAR(MAX),
TASK_ACTIVATION VARCHAR(MAX),
MODULE_NAME VARCHAR(MAX),
RES_ID VARCHAR(MAX)
);